version: "3"
services:
  hh_db:
    image: mysql/mysql-server:8.0.23
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: PASSWORD
    container_name: wordpress_db_hh

  wordpress:
    depends_on:
      - hh_db
    image: wordpress:latest
    ports:
      - 127.0.0.1:668:80
    restart: always
    environment:
      VIRTUAL_HOST: services.home
      VIRTUAL_PORT: 80
      NETWORK_ACCESS: internal
      WORDPRESS_DB_HOST: hh_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: PASSWORD
      WORDPRESS_DB_NAME: wordpress
    container_name: wordpress_hh

volumes:
  db_data:


networks:
  default:
    external:
      name: reverse-proxy-network
